language: ruby
rvm:
- 2.0.0-p481
branches:
  only:
  - master
install:
- travis_retry bundle install
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  api_key:
    secure: AQnPH8t4ptginTNcVt4RKcWDbUkWI+tNtzfeOAg0NVLFGDtoh2urof4Cq0sLTz8kiOVoPLg3R28RQ2p0pid3zTfFzjH+Obvbu0qoiEUjoYqrbanAtk/QrzEGOROhED8Cdc3Zq77+6pLAo/M6yT22DdiPqTvQids2MABdoXogY0N1h2cejCdmqbjkvlyD5vZJQZ3IAgG3qykXgd5v1PI6c5mT0vzd9s+VAuJu2uEQ83/b192SN+YqfX+WGwiLkRIi/YvYop5kRG0p6HajSpk0fGGiHZsWTbel93BzJPDlLvz76mtDXCdNz7KrCtjoDhHnthDTlL9WN3RCWHNyeSb5nygWmz9jNWlsASLEUvGcDrvwaqO6xxcbDzbhNA3vE9qsCj4nLpAu5yDqZYpxCTyjF41mYXsOqB/VZzCm6hpKk+sglerghHHWgoLe1lp6c/0LeljeWrpc33B3J2yt9Q850I1NxLFv+IWIo1ZFYbi6ootRMBJ5e6773HfFsR+yEbg6hrSg/U+YZwgMngGT1LhUkYHy+wQY1z02AJPH86LnlM/l6BoZpJ0CplITJ5TAFoJMOido2wdVg9NBZ554ZTo8uwlC7M5NGITtVFoe80sBArS75J9KpxW6Gq55gOQqI6g9zKCrwY6GO5/DFxB9A8xtnV1JSY2nsu5v77nWAJNI5wg=
  app: peaceful-thicket-3829
  run:
    - "rake db:migrate"
    - restart