development:
 adapter: postgresql
 encoding: utf8
 database: project_development
 pool: 5

test:
 # <<: *default
 database: travis-test_test
 adapter: postgresql
 database: travis_ci_test
 username: postgres

production:
 adapter: postgresql
 encoding: utf8
 database: project_production
 pool: 5

# cucumber:
#  <<: *TEST